version: "3.9"

services:
  http-service:
    build:
      context: .
      dockerfile: ./cmd/server/Dockerfile
    environment:
      - ADI_PROFILE=local
      - ADI_PROFILE_NAME=http-service
      - HTTP_PORT=8080
    ports:
      - "8080:8080"

  traffic:
    build:
      context: .
      dockerfile: ./cmd/traffic/Dockerfile
    environment:
      - ADI_PROFILE=local
      - ADI_PROFILE_NAME=traffic-generator
      - TARGET_HOST=http-service
      - HTTP_PORT=8080
      - TOTAL_REQUESTS=10
      - REQUEST_DELAY_MS=500
    depends_on:
      - http-service
