version: "3.9"

services:
  http-service:
    build:
      context: .
      dockerfile: ./cmd/server/Dockerfile
    environment:
      - HTTP_PORT=8080
    ports:
      - "8080:8080"

  profiler:
    build:
      context: .
      dockerfile: ./cmd/profiler/Dockerfile
    environment:
      - HTTP_PORT=8080
      - OUTPUT_PATH=/output/ebpf_http.log
    privileged: true
    pid: host
    security_opt:
      - apparmor=unconfined
    volumes:
      - ./output:/output
    depends_on:
      - http-service

  traffic:
    build:
      context: .
      dockerfile: ./cmd/traffic/Dockerfile
    environment:
      - TARGET_HOST=http-service
      - HTTP_PORT=8080
      - TOTAL_REQUESTS=50
      - REQUEST_DELAY_MS=500
    depends_on:
      - http-service
